# Generated by Django 5.0.3 on 2024-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Main_post', 'Main_post'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Gallary', 'Gallary'), ('Editors_Pick', 'Editors_Pick')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
