# Generated by Django 5.0.3 on 2024-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0004_remove_post_category_alter_post_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=12)),
                ('event_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
