# Generated by Django 5.0.3 on 2024-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0006_alter_client_date_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
